<a href="https://colab.research.google.com/github/DilaraKardas/letterRecognitionDataSetAnalysis/blob/main/letterRecognitionDataSetAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [15]:
from numpy import extract
import zipfile
zip_path= "/content/drive/MyDrive/letterRecognitionDS/letter+recognition.zip"
extract_path="/content/letterRecogniton"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
  zip_ref.extractall(extract_path)

print("ds çıkartıldı")

ds çıkartıldı

In [25]:
file="/content/letterRecogniton/letter-recognition.data"
df = pd.read_csv(file, header=None)
df.head()

  0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
0  T   2   8   3   5   1   8  13   0   6   6  10   8   0   8   0   8
1  I   5  12   3   7   2  10   5   5   4  13   3   9   2   8   4  10
2  D   4  11   6   8   6  10   6   2   6  10   3   7   3   7   3   9
3  N   7  11   6   6   3   5   9   4   6   4   4  10   6  10   2   8
4  G   2   1   3   1   1   8   6   6   6   6   5   9   1   7   5  10

In [26]:
df.describe

<bound method NDFrame.describe of       0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
0      T   2   8   3   5   1   8  13   0   6   6  10   8   0   8   0   8
1      I   5  12   3   7   2  10   5   5   4  13   3   9   2   8   4  10
2      D   4  11   6   8   6  10   6   2   6  10   3   7   3   7   3   9
3      N   7  11   6   6   3   5   9   4   6   4   4  10   6  10   2   8
4      G   2   1   3   1   1   8   6   6   6   6   5   9   1   7   5  10
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
19995  D   2   2   3   3   2   7   7   7   6   6   6   4   2   8   3   7
19996  C   7  10   8   8   4   4   8   6   9  12   9  13   2   9   3   7
19997  T   6   9   6   7   5   6  11   3   7  11   9   5   2  12   2   4
19998  S   2   3   4   2   1   8   7   2   6  10   6   8   1   9   5   8
19999  A   4   9   6   6   2   9   5   3   1   8   1   8   2   7   2   8

[20000 rows x 17 columns]>

In [27]:
s = pd.Series([1,2,3])
s.describe()

count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
dtype: float64

In [30]:
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
dtype: int64